name: .NET 

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    env: 
      DYLD_FALLBACK_LIBRARY_PATH: /usr/local/opt/openssl@1.1/lib
      CLR_OPENSSL_VERSION_OVERRIDE: 1.1 
    steps:
    - uses: actions/checkout@v2
 #   - name: Set DYLD env variable
 #     run: |
 #       echo 'DYLD_FALLBACK_LIBRARY_PATH=$DYLD_FALLBACK_LIBRARY_PATH:/usr/local/opt/openssl@1.1/lib' >> $GITHUB_ENV

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.x'
    - name: Print env variables
      run: printenv
    - name: Get OpenSsl version
      run: openssl version
    - name: Display OpenSsl lib
      run: ls /usr/local/opt/openssl@1.1/lib
    - name: Display OpenSsl lib 2
      run: ls /usr/local/Cellar/openssl@1.1/1.1.1i/lib
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
